### ISSUE TITLE
Preserve contributors

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/KeyboardKitSwiftUI#11]
Hey @Antonito and @Brennanium 

As I'm about to move this repo into the main one, do you have any idea how to preserve contributor information? I'd like you to still have all PRs and contributions intact after the move, but perhaps this can't be done?

**Comment by Antonito** [comment]
It depends on your merging strategy.

If you merge repos by simply copying files, all commit info will obviously be lost, but you can also merge with git.
You can stash everything into a single commit – which would be the cleanest way imo, but I'm pretty sure contributors infos will be lost. Or, you can just merge all the commits from here to the other repo, and contributors info will be preserved.

Personally, it's not a big deal if my PR gets lost during the merging process :)

**Comment by Brennanium** [comment]
Hmmmm... I could be wrong, but this looks pretty promising: [link](https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories), specifically the answers involving `--allow-unrelated-histories`

What do you plan on doing with this old repo?  Just archiving it?

If worst comes to worst, not having contributor info in the main repo isn't the biggest deal to me; if you are just gonna archive this repo then there'll still be some sort of record of our contributions at least, right?

**Comment by danielsaidi** [comment]
Thanks, I'll check it out and see what I can do. Another option is that I tell you when I'm moving over the parts that you've contributed on and that you move them as a PR.

The repository will be around for quite some time, at least until I release KK 5.

**Comment by danielsaidi** [comment]
@Antonito @Brennanium I unfortunately don't seem to get merging and keeping contributor info to work. I will begin moving stuff from this repo to the main repo tonight. If I see something that is related to what you've contributed with before, perhaps I could ping you and let you move it as a PR? And if you don't care or have time, just lmk then and I'll do it :)

**Comment by danielsaidi** [comment]
If you want to, you can create a PR for the 289695a4ef5fc40e781d8b5a733fc3ec9e566acd

**Comment by danielsaidi** [comment]
@Antonito You read my mind regarding the resources, thanks! :D

**Comment by Antonito** [comment]
@danielsaidi Hahaha no problem :)

**Comment by danielsaidi** [comment]
@Brennanium Perhaps you could add everything from KKSwiftUI's `Layout` and `System` to the main repo? :)

**Comment by danielsaidi** [comment]
@Brennanium I have moved everything else from the repo, so just lmk if you want to add the two folders above to the main repo as a PR, and I'll merge it. After that, I can start working on the main branch's `v4.0`.

**Comment by danielsaidi** [comment]
@Brennanium I noticed that the PR merged into `master` first after merging. I'll see if I can merge it directly from your repo instead.

**Comment by danielsaidi** [comment]
Perfect, your commits are now merged into `v4.0` 🎉

Everything from this repo is now in the main repo's `v4.0` branch, so I can now start working on the 4.0. Hopefully we can have a release candidate ready in February.

**Comment by Brennanium** [comment]
Awesome!  Now that the repos are merged, I have some ideas for 4.0 that I'll test out 👍🏻

**Comment by danielsaidi** [comment]
Sounds great! I will begin to remove old deprecations, remove no longer needed protocols and classes (like replacing `KeyboardContext` and `StandardKeyboardContext` with `ObservableKeyboardContext`, which I'll rename) etc. Things will become so much cleaner.
